### ISSUE TITLE
Reusing UsbRequest objects instead of creating new one

### ISSUE THREAD

**Issue by lukegluke** [kai-morich/usb-serial-for-android#1]
Hi,

For now using library UsbRequestJNI is logging an init and close messages for every transaction over the USB interface (at least for CP21xx and FTDI)
https://stackoverflow.com/questions/28559394/suppress-usbrequestjni-alogd-log-messages

It can be filtered by "setprop log.tag.UsbRequestJNI SUPPRESS", but it seems it would be better to create mUsbRequest object in open() and reuse it in read() instead of creating new one on every read.

**Comment by kai-morich** [comment]
duplicate to https://github.com/mik3y/usb-serial-for-android/issues/232
