### ISSUE TITLE
Possibilities for enabling Arduino SAMD(32 bit ARM cortex M0+) boards to connect with android

### ISSUE THREAD

**Issue by JMJ15** [kai-morich/usb-serial-for-android#3]
Is it possible to connect arduino due or sparkfun SAMD (32 bit ARM cortex M0+) boards with android with this codes? By using below mentioned code?
 customTable.addProduct(0x1234, 0x0001, CdcAcmSerialDriver.class);

**Comment by kai-morich** [comment]
yes, these are all CdcAcm devices, of course you have to use the correct VID/PID

**Comment by JMJ15** [comment]
I downloaded the app from the mentioned link https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal&hl=en_IN
 which is yours from play store. But it did not detect the sparkfun 9DOF IMU Razor SAMD (32 bit ARM cortex M0+) board. It only shows the vendor id and product id with "unknown" as the name at USB Device option in the app. Even if I connect arduino due it is only shows the vendor ID and name as Arduino and product Id with three "?" and did not connect to the serial port. why it maybe?

**Comment by kai-morich** [comment]
the VID/PID of your devices are not known to the app. you have to select the correct driver in the device list

**Comment by JMJ15** [comment]
From where the device list can select?

**Comment by kai-morich** [comment]
when clicking on the 'unknown device' you should get a driver list. When a driver is set you can change with 'long click'

**Comment by JMJ15** [comment]
Okay Sir. Let me try with that and will inform you the result. Thanks for your valid time and help. I'm really sorry to ask this. Since I'm Very new to android development.

**Comment by JMJ15** [comment]
Thanks for your help. Now it got connected and working fine. Thanks a Lot for your help
